load("@npm_ts//@bazel/typescript:index.bzl", "ts_config", "ts_project")

package(default_visibility = ["//visibility:public"])
exports_files(["tsconfig_base.json"])

ts_config(
    name = "tsconfig",
    src = "tsconfig_base.json",
)